### ISSUE TITLE
Problem with cheat code theotherside

### ISSUE THREAD

**Issue by Terax235** [leveleditor/CrystAlien-Conflict-Flash-Wrapper#2]
In Alien level 5 theotherside-mode you automatically lose if the Speeder get's destroyed (that shouldn't happen because you are at the Astro side).

**Comment by Brian151** [comment]
"theotherside" only really exists because of a now deeply questioned decision to make an unintended side effect of the testmode level skip cheat into a feature.

dealing with problems such as you've mentioned in effect requires patching the level, itself.

```actionscript
if (this.level == 15)
			{
			var isBuggy = this.findUnit("UE_evil");
			if (!isBuggy)
				this.lose();
			}```

We've decided for the time being not to pursue that, so bugs like this will remain. The existing codebase just doesn't suit these kinds of modifications, we often end-up breaking stuff or having major conflicts and stuff.

I hope you understand?

And sorry for the delayed response, I've been combinations of stressed/busy, and Josh has just been busy.

@leveleditor anything you wish to add?

**Comment by leveleditor** [comment]
That pretty much summarizes what the real issue is here.

We decided a while back to fix the bug with the beeblebrox/testmode cheat where you could use the level skip to end up playing as the opposing team on just about any level.
The fix involved changing the level skip to put you on the correct team instead. So we decided that since the bug was well known and kinda fun to play around with, we wanted to keep it around somehow, so we essentially turned the bug into a cheat code - in effect making the bug look like a feature.

Now since the levels were absolutely not intended to be played as the opposing team (save for a few bits of code that interestingly did account for that), what you end up with is a cheat code "theotherside" that is better than the original bug, but still has most of it's original problems. So the cheat code was only meant to keep access to the bug for fun, and not really to add a new fully working game mode.

That said, we did try to accommodate this mode by adding some conditions to fix certain bugs while playing as the opposing team, but in doing so we also ended up creating unintended side effects while playing the levels normally, as the levels were never supposed to handle this situation.

I'll see if I can come up with a patch for this specific problem, however we can't continue to patch all of the broken edge cases that come along with playing as the other side, so the future of this cheat code is uncertain at this point.

**Comment by Terax235** [comment]
Okay. Thanks for your answers, I can understand that.

**Comment by Brian151** [comment]
@Terax235 

Believe me, it is actually frustrating how many things we can't really change right now. There's a lot of crap that's surrounded by if statements... 

The plan, if we can get far is to either port the game, or update the engine and re-compile the main swf. We probably won't do the latter. The flash wrapper kinda exists so the "secret stuff" in the code remains secret and such. We have since been given permission to release the source code (with exceptions of certain DEFINITELY secret stuff), but we're trying to document it sufficiently so that it may be made sense of. We stand by our agreement NOT to share the FLAs, though. However, we will share/re-use certain scrapped things if we find them. This is how the "bodyguard" level was added. I was digging through an old fla and found the code and the data. All we didn't have is the dialogue, and the original developer doesn't remember much about it. (actually, he now considers me the resident expert on HIS game! XD)

anyways, here's an idea of the current engine:
http://crystalien-redux.com/uploads/public/resources/CAC_SOURCE_CODE/

If you're not aware of these, you may also want to check-out:
https://github.com/Brian151/CAC-Unit-Editor
https://github.com/Brian151/CAC-Building-Editor
or the live versions:
http://crystalien-redux.com/uploads/ETX/Util/App/cac_building_editor/buildingEditor.html
http://crystalien-redux.com/uploads/ETX/Util/App/cac_unit_editor/unitEditor.html

And thanks for understanding, we've had less than reasonable individuals in the past...

**Comment by leveleditor** [comment]
This is now fixed. The update will go live on the website soon.

**Comment by leveleditor** [comment]
The update is now live on the website. I forgot about it for a while there due to other things going on.

**Comment by Brian151** [comment]
Alright...
